### ISSUE TITLE
Cannot read property 'bgColorGradient' of undefined     at a.setLightPreset

### ISSUE THREAD

**Issue by orbjeff** [Autodesk-Forge/forge-rcdb.nodejs#43] opened 2018-01-28 14:34 UTC
Windows 10 / Chrome Version 64.0.3282.119 (Official Build) (64-bit) / Node.js 9.4

The application starts without any errors but when I navigate to one of the pages which load the viewer the following error is thrown:

THREE.WebGLRenderer 71
Viewer.Configurator.js:802 Viewer Initialization Error: 
Viewer.Configurator.js:803 TypeError: Cannot read property 'bgColorGradient' of undefined
    at a.setLightPreset (https://developer.api.autodesk.com/derivativeservice/v2/viewers/viewer3D.min.js?v=3.3:23:24618)
    at a.e.setLightPreset (https://developer.api.autodesk.com/derivativeservice/v2/viewers/viewer3D.min.js?v=3.3:30:13054)
    at ViewerConfigurator._callee4$ (http://localhost:3000/3.js:4225:24)
    at tryCatch (http://localhost:3000/bundle.js:76650:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/bundle.js:76884:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/bundle.js:76702:21)
    at step (http://localhost:3000/bundle.js:22882:30)
    at http://localhost:3000/bundle.js:22900:14
    at new Promise (<anonymous>)
    at new F (http://localhost:3000/bundle.js:2078:28)
    at ViewerConfigurator.<anonymous> (http://localhost:3000/bundle.js:22879:12)
    at ViewerConfigurator.onViewerCreated (http://localhost:3000/3.js:4323:22)
    at ViewerConfigurator.onViewerCreated (http://localhost:3000/bundle.js:55530:30)
    at Object.onViewerCreated (http://localhost:3000/3.js:4420:19)
    at Viewer.componentDidMount (http://localhost:3000/3.js:3125:20)
    at Viewer.proxiedComponentDidMount (http://localhost:3000/bundle.js:55552:40)

On line 716 a reference to viewerTheme.lightPreset return undefined.
viewer.setLightPreset(viewerTheme.lightPreset)

I'm not seeing a lightPreset under appState.storage.theme.viewer  - Should it be here?

![lightpreseterror](https://user-images.githubusercontent.com/35840308/35483158-60cb31b0-0404-11e8-8195-667548d653ff.png)

My temporary workaround is to just test for null and allow the viewer to continuing loading:

`if (viewerTheme.lightPreset) {
        viewer.setLightPreset(viewerTheme.lightPreset)
      }`

In development.config.js I'm referencing viewer version 3.3 and and source code is from a new clone today.

    viewer: {
      //viewer3D: '/resources/libs/lmv/viewer3D.js',
      viewer3D: 'https://developer.api.autodesk.com/derivativeservice/v2/viewers/viewer3D.min.js?v=3.3',

      //threeJS: '/resources/libs/lmv/three.js',
      threeJS: 'https://developer.api.autodesk.com/derivativeservice/v2/viewers/three.min.js?v=3.3',

      //style: '/resources/libs/lmv/style.css'
      style: 'https://developer.api.autodesk.com/derivativeservice/v2/viewers/style.min.css?v=3.3'
    }

**Comment by orbjeff** [comment] 2018-01-29 18:09
Yeah I can't pin this one down either. It seems like it would start here:

\store\app.js line 204
`  const storage = storageSvc.load(
    'AppState.storage',
    defaultAppState)`

And when the item is pulled back out here:
StorageSvc.js line 57
`  load (key, defaultValue = {}) {

    const storageKey = this.getStoragekey(key)

    const item = Lockr.get(storageKey) || defaultValue

    if (item.storageVersion) {

      if (this.currentStorageVersion > item.storageVersion) {
        return defaultValue
      }
        
      return item.__array || item
    }

    return defaultValue
  }`

It no longer has the lightPreset property. The defaultValue that's passed in has the lightPreset property so yes if there is no "AppState.storage" item in the collection it should be ok. I think that's what you mean when you say to clear  the storage entry.
![storage_value](https://user-images.githubusercontent.com/35840308/35526221-59590acc-04ec-11e8-882c-b67678e95928.png)

Just testing for undefined as I mentioned above is working for me so this was more of a heads up to anyone else who may be trying to get the viewer to load but only see the dots animating.

I ended up using this code in the Viewer.Configurator.js file:
`      if (viewerTheme.lightPreset) {

        viewer.setLightPreset(viewerTheme.lightPreset)
      } else {

        viewer.setLightPreset(Autodesk.Viewing.Private.LightPresets.length - 1)
      }`

**Comment by leefsmp** [comment] 2018-01-29 21:37
I tested on Win 10 with Chrome 64 and cannot reproduce it, so I will close it for the time being. Feel free to add further comments if needed.

**Closed by leefsmp** 2018-01-29 21:37 UTC
